name: Bug Report
description: Report something that's broken
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What's broken?
      description: Clear description of the bug
      placeholder: "Describe what's not working as expected..."
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "Describe what you expected to happen..."
    validations:
      required: false
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Describe what actually happened..."
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or logs
      placeholder: "Paste any relevant error messages here..."
      render: shell
    validations:
      required: false
      
  - type: textarea
    id: requirements
    attributes:
      label: Fix Requirements
      description: What needs to be done to fix this bug?
      value: |
        - [ ] Reproduce the issue
        - [ ] Identify root cause
        - [ ] Implement fix
        - [ ] Add test to prevent regression
        - [ ] Verify fix resolves the issue
    validations:
      required: false