name: Bug Report
description: Report something that's broken
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: all_details
    attributes:
      label: Bug Report
      description: Fill out all sections below
      value: |
        ## What's broken?
        <!-- Describe the bug clearly -->
        
        
        ## Steps to Reproduce
        1. 
        2. 
        3. 
        
        ## Error Logs (if any)
        ```
        
        ```
    validations:
      required: true