name: Bug Report
description: Report something that's broken or not working as expected
title: "[BUG]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before You Submit
        Please search existing issues to avoid creating duplicates.
        
  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: Link any related or duplicate issues (use #issue_number)
      placeholder: "#123, #456"
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What's broken? Be specific and clear.
      placeholder: |
        When I try to...
        I expect...
        But instead...
    validations:
      required: true
        
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - "Critical - System unusable"
        - "High - Major functionality broken"
        - "Medium - Feature partially broken"
        - "Low - Minor issue"
      default: 2
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part is broken? (select all that apply)
      multiple: true
      options:
        - Frontend UI
        - Backend API
        - Database
        - Authentication
        - GitHub Actions
        - Agent System
        - MCP Servers
        - Documentation
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Where does this bug occur?
      placeholder: |
        - OS: Windows/Mac/Linux
        - Browser: Chrome 120
        - Node version: 18.x
        - Claude Code version: 
      value: |
        - OS: 
        - Browser: 
        - Node version: 
        - Claude Code version: 
        
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Include any error messages or logs
      render: shell
      placeholder: |
        Paste error messages here...
        
  - type: dropdown
    id: regression
    attributes:
      label: Is this a regression?
      description: Did this work before?
      options:
        - "Yes - Used to work"
        - "No - Never worked"
        - "Not sure"
      default: 2
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and this is not a duplicate
          required: true
        - label: I can reproduce this bug consistently
          required: false
        - label: I'm willing to help fix this bug
          required: false