blank_issues_enabled: false
contact_links:
  - name: Start a Discussion
    url: https://github.com/vanman2024/multi-agent-claude-code/discussions/new
    about: For questions, ideas, or topics that need community input
  - name: Documentation
    url: https://github.com/vanman2024/multi-agent-claude-code/blob/main/README.md
    about: Check our documentation first
  - name: Agent Overview
    url: https://github.com/vanman2024/multi-agent-claude-code/blob/main/agent-overview.md
    about: Learn about our agent system