name: Discussion Needed
description: Topics that need community input before becoming issues
title: "[DISCUSS]: "
labels: ["discussion-needed", "question"]
body:
  - type: markdown
    attributes:
      value: |
        ## This Might Be Better as a Discussion
        If you're not sure about implementation details, consider starting a Discussion instead.
        Issues should be actionable. Discussions are for brainstorming.
        
  - type: dropdown
    id: discussion_type
    attributes:
      label: Discussion Type
      description: What kind of input do you need?
      options:
        - "Architecture Decision - How should we build this?"
        - "Feature Design - What should this look like?"
        - "Problem Definition - Is this really an issue?"
        - "Solution Brainstorm - What are our options?"
        - "Community Feedback - What do users think?"
      default: 1
    validations:
      required: true
      
  - type: textarea
    id: topic
    attributes:
      label: Topic Overview
      description: What needs to be discussed?
      placeholder: |
        We need to decide...
        The question is...
        Options include...
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Background Context
      description: Why does this matter?
      placeholder: |
        This came up because...
        Users have been asking for...
        The current limitation is...
    validations:
      required: true
      
  - type: textarea
    id: options
    attributes:
      label: Options to Consider
      description: What are the possibilities?
      value: |
        Option 1: 
        - Pros: 
        - Cons: 
        
        Option 2:
        - Pros:
        - Cons:
        
        Option 3:
        - Pros:
        - Cons:
        
  - type: textarea
    id: questions
    attributes:
      label: Key Questions
      description: What needs to be answered?
      value: |
        - [ ] Should we...?
        - [ ] How should...?
        - [ ] What about...?
        - [ ] Who would...?
        
  - type: textarea
    id: stakeholders
    attributes:
      label: Who Should Participate?
      description: Tag relevant people or teams
      placeholder: "@frontend-team, @backend-team, @security-team"
      
  - type: dropdown
    id: timeline
    attributes:
      label: Decision Timeline
      description: When do we need to decide?
      options:
        - "Urgent - This week"
        - "Soon - Next 2 weeks"
        - "Normal - This month"
        - "Whenever - No rush"
      default: 2
      
  - type: input
    id: convert_to_discussion
    attributes:
      label: Convert to Discussion?
      description: Should this be a GitHub Discussion instead? (Type YES to acknowledge)
      placeholder: "YES - I should create a Discussion instead"
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Before Creating Issue
      options:
        - label: I understand this might be better as a Discussion
          required: true
        - label: This needs input from multiple people
          required: false
        - label: The implementation is not clear yet
          required: false