name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE]: "
labels: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What kind of change is this?
      options:
        - "New Feature"
        - "Enhancement"
        - "Refactor"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you want to build or improve?
      placeholder: "Describe the feature or enhancement..."
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem it Solves
      description: What problem does this feature solve?
      placeholder: "Explain the problem or need this addresses..."
    validations:
      required: false
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: "Describe how you envision this feature working..."
    validations:
      required: false
      
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know when this is complete?
      value: |
        - [ ] Design and plan implementation approach
        - [ ] Implement core functionality
        - [ ] Add necessary tests
        - [ ] Update documentation if needed
        - [ ] Verify feature works as expected
    validations:
      required: false
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?
      placeholder: "List any alternative solutions you've considered..."
    validations:
      required: false