name: Feature / Enhancement
description: Suggest a new feature or improvement
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: all_details
    attributes:
      label: Details
      description: Fill out all sections below
      value: |
        ## Description
        <!-- What do you want to build/improve? -->
        
        
        ## Acceptance Criteria
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true
      
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What kind of change is this?
      options:
        - "New Feature"
        - "Enhancement"
        - "Refactor"
    validations:
      required: true