name: Feature / Enhancement
description: Suggest a new feature or improvement
title: "[FEATURE]: "
labels: ["feature"]
body:
  - type: textarea
    id: all_details
    attributes:
      label: Feature Request
      description: Fill out all sections below
      value: |
        ## Type
        <!-- Choose one: New Feature / Enhancement / Refactor -->
        New Feature
        
        ## Description
        <!-- What do you want to build/improve? -->
        
        
        ## Acceptance Criteria
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true