name: Simple Issue
description: Create a work item with clear implementation details
title: "[Type]: "
labels: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What kind of work is this?
      options:
        - feature
        - bug
        - infra
        - architecture
        - chore
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Goal
      description: What problem are we solving or goal are we achieving?
      placeholder: |
        Users can't log in with their email address.
        We need an API endpoint to fetch user profiles.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: How should this be implemented? Be specific.
      placeholder: |
        1. Create /api/auth/login endpoint
        2. Accept email and password in POST body
        3. Validate against Supabase auth
        4. Return JWT token and user profile
        5. Handle errors (wrong password, user not found)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know when this is done?
      placeholder: |
        - [ ] Endpoint responds to POST /api/auth/login
        - [ ] Returns 200 with token on success
        - [ ] Returns 401 on bad credentials
        - [ ] Returns 404 on unknown user
        - [ ] Tests pass
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High (This sprint)
        - Medium (Next sprint)
        - Low (Backlog)
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Size
      description: How much work is this?
      options:
        - XS (< 1 day)
        - S (1-2 days)
        - M (3-5 days)
        - L (1 week+)
    validations:
      required: true