name: Task
description: Create a simple task or chore
title: "[TASK]: "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: What needs to be done?
      description: Describe the task clearly
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: Break it down if needed
      value: |
        - [ ] 
        - [ ] 
      
  - type: dropdown
    id: milestone
    attributes:
      label: Target Milestone
      description: When should this be completed?
      options:
        - "Current Sprint"
        - "Next Sprint"
        - "Backlog"
    validations:
      required: true