name: Task
description: Create a simple task or chore
title: "[TASK]: "
labels: ["task"]
body:
  - type: textarea
    id: all_details
    attributes:
      label: Task
      description: Fill out all sections below
      value: |
        ## What needs to be done?
        <!-- Describe the task clearly -->
        
        
        ## Steps
        - [ ] 
        - [ ] 
    validations:
      required: true