[versioning]
package = "example_package"
source = "src/config/package.toml"

[package]
name = "example_package"
path = "src"
test_command = "pytest tests/backend"

[package.manifest]
version = "VERSION"
requirements = "requirements.txt"
install = "install.sh"
cli = "example-cli"

[deploy]
target = "/abs/path/to/deploy"
subdirectory = "project-sync/example_package"
