name: Project Sync Backend Tests

on:
  pull_request:
    paths:
      - 'project-sync/testing/backend-tests/**'
      - 'project-sync/scripts/**'
      - 'project-sync/**.py'
      - 'project-sync/**/pytest.ini'
  push:
    branches: [ main, develop ]
    paths:
      - 'project-sync/testing/backend-tests/**'

jobs:
  python-backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project-sync/testing/backend-tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio inline-snapshot
          # Optional MCP dependency
          pip install fastmcp || echo "fastmcp optional"

      - name: Run fast backend tests (CLI-first defaults)
        run: |
          pytest -m "not slow and not client_process" -q

