# Project Operations Config
# Template: Customize for your project
versioning:
  strategy: conventional_commits
  source: pyproject.toml

targets:
  - /tmp/agentswarm-staging

release:
  changelog: true
  tag_prefix: v

qa:
  lint: true
  typecheck: true
  tests: "not slow"

env:
  wsl_check: true

hooks:
  auto_sync: false
