name: Auto Assign Issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if creator is team member
        id: check-team
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.issue.user.login;
            
            // Mechanical check - like a valve checking pressure
            // These are team members who can self-assign
            const teamMembers = [
              'vanman2024',
              'vanman2025',
              // Add team members here
            ];
            
            // Simple mechanical logic - not intelligent decision making
            const isTeamMember = teamMembers.includes(creator);
            const isBot = creator.includes('[bot]') || creator.includes('bot');
            
            // Only auto-assign if:
            // 1. Creator is in team list AND
            // 2. Creator is not a bot
            const shouldAssign = isTeamMember && !isBot;
            
            console.log(`Creator: ${creator}, Team member: ${isTeamMember}, Should assign: ${shouldAssign}`);
            core.setOutput('should-assign', shouldAssign);
            core.setOutput('creator', creator);
      
      - name: Auto assign issue to creator (if team member)
        if: github.event_name == 'issues' && steps.check-team.outputs.should-assign == 'true'
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: ${{ steps.check-team.outputs.creator }}
          
      - name: Add supplemental labels based on metadata
        uses: actions/github-script@v7
        with:
          script: |
            // Issue templates already add type labels (bug, feature, task, hotfix)
            // This only adds supplemental labels based on issue body metadata
            
            const body = context.payload.issue?.body || '';
            const labels = [];
            
            // Add 'documentation' label if it's a docs-related issue
            if (body.includes('**Type**: Documentation') || 
                (body.toLowerCase().includes('documentation') && 
                 body.toLowerCase().includes('update'))) {
              labels.push('documentation');
            }
            
            // Add 'urgent' label for P0 priority issues (in addition to hotfix template)
            if (body.includes('**Priority**: P0')) {
              labels.push('urgent');
            }
            
            // Add 'needs-triage' if no priority is specified
            if (!body.includes('**Priority**:')) {
              labels.push('needs-triage');
            }
            
            if (labels.length > 0) {
              console.log(`Adding supplemental labels: ${labels.join(', ')}`);
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labels
              });
            }
            
