name: Auto Checkbox Updater

on:
  push:
    branches-ignore:
      - main  # Don't run on main branch commits

permissions:
  issues: write
  contents: read

jobs:
  update-checkboxes:
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Checkboxes Based on Commits
        uses: actions/github-script@v7
        with:
          script: |
            console.log('🔍 Analyzing commits for checkbox updates...');
            
            // Get the branch name
            const branch = context.ref.replace('refs/heads/', '');
            console.log(`Branch: ${branch}`);
            
            // Extract issue number from branch name (e.g., "126-fix-work-command")
            const issueMatch = branch.match(/^(\d+)-/);
            if (!issueMatch) {
              console.log('❌ No issue number found in branch name');
              return;
            }
            
            const issueNumber = parseInt(issueMatch[1]);
            console.log(`📋 Found issue number: ${issueNumber}`);
            
            // Get the issue
            let issue;
            try {
              const issueResponse = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              issue = issueResponse.data;
            } catch (error) {
              console.log(`❌ Issue #${issueNumber} not found`);
              return;
            }
            
            // Get commit messages from the push
            const commits = context.payload.commits || [];
            if (commits.length === 0) {
              console.log('❌ No commits found');
              return;
            }
            
            console.log(`📝 Analyzing ${commits.length} commits...`);
            
            // Parse issue body for checkboxes
            const body = issue.body || '';
            const checkboxRegex = /^(\s*-)(\s*\[)([ x])(\]\s*)(.+)$/gm;
            let updatedBody = body;
            let updatedCount = 0;
            
            // Look for checkbox completion patterns in commit messages
            commits.forEach((commit, index) => {
              console.log(`Commit ${index + 1}: ${commit.message}`);
              
              // Patterns that indicate checkbox completion:
              // - "✅ Completed: [checkbox text]"
              // - "feat: Add [something] - completes checkbox [text]"
              // - "fix: [something] ✅ [checkbox text]"
              
              const completionPatterns = [
                /✅\s*(?:Completed?:?\s*)?(.+)/i,
                /completes?\s+checkbox:?\s*(.+)/i,
                /(?:feat|fix|docs|chore):\s*(.+?)\s*✅\s*(.+)/i,
                /checkbox\s*(?:complete|done):?\s*(.+)/i
              ];
              
              completionPatterns.forEach(pattern => {
                const match = commit.message.match(pattern);
                if (match) {
                  const completedText = match[1] || match[2];
                  console.log(`🎯 Found completion indicator: "${completedText}"`);
                  
                  // Find matching checkbox in issue body and mark as complete
                  const checkboxPattern = new RegExp(
                    `^(\\s*-)(\\s*\\[)([ ])(\\]\\s*)(.{0,100}${completedText.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}.{0,100})$`,
                    'mi'
                  );
                  
                  if (checkboxPattern.test(updatedBody)) {
                    updatedBody = updatedBody.replace(checkboxPattern, '$1$2x$4$5');
                    updatedCount++;
                    console.log(`✅ Updated checkbox: ${completedText}`);
                  }
                }
              });
            });
            
            // If we updated any checkboxes, update the issue
            if (updatedCount > 0) {
              console.log(`🔄 Updating ${updatedCount} checkboxes in issue #${issueNumber}`);
              
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: updatedBody
              });
              
              // Add a comment about the automatic update
              const commitShas = commits.map(c => c.id.substring(0, 7)).join(', ');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `🤖 **Auto-updated ${updatedCount} checkbox${updatedCount > 1 ? 'es' : ''} from commits**
                
**Commits:** ${commitShas}

${commits.map(c => `- \`${c.id.substring(0, 7)}\` ${c.message}`).join('\n')}

*Updated via commit hook automation* ⚡`
              });
              
              console.log(`✅ Successfully updated ${updatedCount} checkboxes`);
              
              // Trigger the existing issue checklist enforcer to update progress
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: issue.labels.map(l => l.name)  // Trigger label update to fire other hooks
              });
              
            } else {
              console.log('ℹ️ No checkbox completion patterns found in commits');
            }