name: Copilot PR Handler

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  handle-copilot-pr:
    name: Process Copilot PRs
    runs-on: ubuntu-latest
    # Only run for Copilot-created PRs
    if: |
      github.event.pull_request.draft == true && 
      startsWith(github.event.pull_request.head.ref, 'copilot/')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
          fi
          
      - name: Run Tests
        id: tests
        continue-on-error: true
        run: |
          # Run tests if they exist
          if [ -f package.json ] && grep -q "\"test\"" package.json; then
            npm test
            echo "tests_passed=true" >> $GITHUB_OUTPUT
          else
            echo "No tests configured"
            echo "tests_passed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Run Linting
        id: lint
        continue-on-error: true
        run: |
          # Run lint if configured
          if [ -f package.json ] && grep -q "\"lint\"" package.json; then
            npm run lint
            echo "lint_passed=true" >> $GITHUB_OUTPUT
          else
            echo "No linting configured"
            echo "lint_passed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Convert to Ready for Review
        if: steps.tests.outputs.tests_passed == 'true' && steps.lint.outputs.lint_passed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Mark PR as ready for review
          gh pr ready ${{ github.event.pull_request.number }}
          
          # Add label
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-label "copilot-pr,ready-for-merge"
          
          # Add comment
          gh pr comment ${{ github.event.pull_request.number }} --body "✅ **Copilot PR Ready**
          
          - Tests: Passing ✓
          - Linting: Passing ✓
          - Status: Ready for review
          
          This PR was automatically validated and marked as ready.
          
          **Next steps**:
          1. Claude Code will review for completeness
          2. Auto-merge if approved
          3. Pull changes locally with: \`git pull origin main\`"
          
      - name: Request Claude Review
        if: steps.tests.outputs.tests_passed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add label for Claude review
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-label "needs-claude-review"
            
          # Comment to trigger local notification
          gh pr comment ${{ github.event.pull_request.number }} --body "🔍 **Requesting Claude Code Review**
          
          @${{ github.repository_owner }} - Copilot has completed implementation.
          
          Please review with Claude Code:
          \`\`\`bash
          # Pull and review locally
          gh pr checkout ${{ github.event.pull_request.number }}
          # Review with Claude Code agents
          /review-pr ${{ github.event.pull_request.number }}
          \`\`\`"
          
      - name: Auto-merge if Simple
        if: |
          steps.tests.outputs.tests_passed == 'true' && 
          contains(github.event.pull_request.labels.*.name, 'complexity-1')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Enable auto-merge for simple PRs
          gh pr merge ${{ github.event.pull_request.number }} \
            --auto \
            --squash \
            --delete-branch
            
          echo "✅ Auto-merge enabled for simple PR"