name: Enforce PR Checkboxes

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted, edited, dismissed]
  issue_comment:
    types: [created, edited, deleted]

permissions:
  pull-requests: read
  checks: write
  statuses: write

jobs:
  require-checkboxes:
    name: Require All Checkboxes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.issue.pull_request
    steps:
      - name: Require Checklist
        uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true  # Fail if no checklists found
          skipDescriptionRegex: .*\(optional\).*  # Skip items marked as optional
          skipDescriptionRegexFlags: i
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Comment Status
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = context.issue.number || context.payload.pull_request.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: '❌ **PR cannot be merged**: Not all required checkboxes are checked. Please complete all checklist items before merging.'
            });