name: Enforce PR Checkboxes

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read
  checks: write
  statuses: write

jobs:
  require-checkboxes:
    name: Require All Checkboxes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !startsWith(github.head_ref, 'hotfix-')
    steps:
      - name: Require Checklist
        uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true  # Fail if no checklists found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Comment Status
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = context.issue.number || context.payload.pull_request.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: '❌ **PR cannot be merged**: Not all required checkboxes are checked. Please complete all checklist items before merging.'
            });
            
  hotfix-bypass:
    name: Hotfix Bypass
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'hotfix-')
    steps:
      - name: Auto-pass for hotfix
        run: |
          echo "🚨 HOTFIX DETECTED - Bypassing checkbox requirements"
          echo "Branch: ${{ github.head_ref }}"
          echo "This is a critical fix that needs immediate deployment"
          exit 0