name: Quick Fix Handler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-quick-fix:
    name: Detect and Handle Quick Fix PRs
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if Quick Fix
        id: check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title.toLowerCase();
            const body = pr.body || '';
            
            // Detect quick fix patterns
            const isQuickFix = 
              title.startsWith('chore:') ||
              title.startsWith('fix:') && title.includes('typo') ||
              title.startsWith('docs:') && !title.includes('major') ||
              body.includes('Quick fix - no issue needed') ||
              pr.head.ref.startsWith('chore/') ||
              pr.head.ref.startsWith('quick/');
            
            // Check if PR references an issue
            const hasIssue = body.match(/(closes|fixes|resolves)\s+#\d+/i);
            
            if (isQuickFix && !hasIssue) {
              console.log('✅ Detected Track 2 Quick Fix PR');
              
              // Add quick-fix label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['quick-fix']
              });
              
              // Add comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `🚀 **Quick Fix Detected**\n\nThis PR follows Track 2 (Direct PR) workflow.\n\n**Fast-track enabled:**\n- No issue required\n- Minimal checks only\n- Auto-merge available when green`
              });
              
              // Enable auto-merge if checks pass
              if (pr.draft === false) {
                try {
                  await github.rest.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    auto_merge: {
                      merge_method: 'squash'
                    }
                  });
                  console.log('Auto-merge enabled');
                } catch (e) {
                  console.log('Could not enable auto-merge:', e.message);
                }
              }
            }