
name: Scheduled Maintenance

on:
  schedule:
    # Runs at 2 AM UTC every Monday
    - cron: '0 2 * * 1'
  workflow_dispatch:  # Allow manual trigger

jobs:
  dependency-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for outdated dependencies
        run: |
          npm outdated || true

      - name: Create issue for updates
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString().split('T')[0];
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[MAINTENANCE] Weekly dependency check - ${date}`,
              body: `## Weekly Dependency Review

              - [ ] Review npm outdated results
              - [ ] Update minor versions
              - [ ] Test after updates
              - [ ] Update documentation if needed

              This issue was automatically created by the scheduled workflow.`,
              labels: ['maintenance', 'dependencies']
            });

  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Close stale issues
        uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been inactive for 30 days.'
          close-issue-message: 'Closing due to inactivity.'
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'stale'
